### ISSUE TITLE
Windows 11: app stops working after sometime and the taskbar reverts to auto-hide even on desktop

### ISSUE THREAD

**Issue by JediRhymeTrix** [ChanpleCai/SmartTaskbar#101]

**Comment by ChanpleCai** [comment]
Does it always stop working after running for a while?

**Comment by JediRhymeTrix** [comment]
@ChanpleCai Yes. After a working as expected a few times, it just reverts to auto-hide. Also  double clicking the overflow menu icon doesn't toggle auto mode, it just switches between always show and auto-hide. Is that expected?

**Comment by JediRhymeTrix** [comment]
I don't think that is the case, because it is highly unlikely that some invisible full-screen application is running some time after logging in and then staying on-screen indefinitely. 

I can see where you're coming from, though. Wallpaper Engine used to cause this issue for the same reason you're implying, but I can assure you, that's not running.

I think this is a different issue. Are there any logs you'd be interested in checking out?

**Comment by JediRhymeTrix** [comment]
Looks like this was resolved in a subsequent update. Thanks!
