### ISSUE TITLE
任务栏隐藏的逻辑问题

### ISSUE THREAD

**Issue by Apple-SteveJobs** [ChanpleCai/SmartTaskbar#107]
1. 当前会判断任务栏与窗体重合便会自动隐藏，我觉得哈，应当仅仅依靠聚焦窗体是否最大化来控制隐藏与否，会解决很多莫名其妙隐藏又显示出来的问题。
2. 当前如果在开始菜单中任何的应用、系统设置或是资源管理器时，任务栏必定会隐藏一下，然后跳出来。
3. 系统win11 21H2，从微软商店下载的本软件。

**Comment by vcup** [comment]
开发者可以试一下题主的解决方案，也许可以解决自述文件提到的一个已知问题
https://github.com/ChanpleCai/SmartTaskbar/blob/b1f53c6b2d56c305ce6e7cbd7d6d599452b23607/README.md?plain=1#L30

**Comment by ChanpleCai** [comment]
试试这个版本： [v1.4.3](https://github.com/ChanpleCai/SmartTaskbar/releases/download/v1.4.3/SmartTaskbar_Setup.exe)
