### ISSUE TITLE
Whenever I get a notification from Steam/Whatsapp my taskbar flickers

### ISSUE THREAD

**Issue by Spontini** [ChanpleCai/SmartTaskbar#108]
As I said on the title, whenever someone texts me from Steam or Whatsapp desktop app taskbar flickers like crazy in auto mode.

**Comment by FernandoPA11** [comment]
Same problem with any notification

**Comment by ChanpleCai** [comment]
try this: [https://github.com/ChanpleCai/SmartTaskbar/releases/tag/v1.4.0](https://github.com/ChanpleCai/SmartTaskbar/releases/tag/v1.4.0)
