### ISSUE TITLE
Windows 8.1: blank tray icon

### ISSUE THREAD

**Issue by CottonEaster** [ChanpleCai/SmartTaskbar#11]
Screenshot:

![image](https://user-images.githubusercontent.com/9998846/41347010-4bbba6d0-6f00-11e8-98d5-3c6dfaa59e5d.png)

SmartTaskbar version: 1.1.6.

By the way: I find your software a useful alternative to the inbuilt, but buggy, function that is built into Windows itself.

**Comment by ChanpleCai** [comment]
![default](https://user-images.githubusercontent.com/17264245/41347949-c5710dac-6f3d-11e8-95ec-0e85f1f90fc1.png)

My fault, I only considered the appearance of the icon on win10. I will make a more suitable icon for win8.1 and earlier systems in next build. 

Work around:  drag the icon onto the taskbar and it will display normally.

**Comment by CottonEaster** [comment]
Thank you for your reply and your committment to fixing the issue. Thank you too for the workaround, which works.

**Comment by ChanpleCai** [comment]
The bug has been fixed in the new version (v1.1.7)
