### ISSUE TITLE
最小化时立即显示任务栏和音量弹出浮窗遮挡bug

### ISSUE THREAD

**Issue by bai12123** [ChanpleCai/SmartTaskbar#115]
1.当窗口最大化后，任务栏隐藏，点击最小化按钮，任务栏还是隐藏状态，需要点击鼠标才会显示出来。正确的做法是像关闭最大化窗口一样，自动显示出任务栏

2. 启动软件后，不管是否最大化窗口。我点击音量，日历，wifi等通知区域图标，弹出的窗口都遮挡了任务栏
![Snipaste](https://user-images.githubusercontent.com/99849852/162641318-031b0967-dfd5-424d-a479-85569e9447c6.png)

**Comment by ChanpleCai** [comment]
是哪个版本的呀，商店下的还是这里？。
第二个是系统在自动隐藏模式下，自带窗口的默认行为。
