### ISSUE TITLE
可否增加一个白名单功能

### ISSUE THREAD

**Issue by vcup** [ChanpleCai/SmartTaskbar#116]
网易云的歌词栏会被算作遮挡任务栏，然后隐藏掉任务栏。但歌词栏是我特地放在任务栏上的，提议增加一个白名单功能，枚举存在的窗体然后让用户选择加入白名单中。

软件版本: 1.4.3
系统版本：Windows 11 21H2

单纯的把歌词栏放到任务栏那不会直接隐藏任务栏，只有将桌面上所有打开的窗口隐藏之后，歌词栏才会开始隐藏任务栏，而且再重新打开窗口也不会再显示
另外，打开开始菜单再关掉开始菜单，歌词栏就不再隐藏任务栏了，但等任务栏又一次被其他窗口隐藏的之后，歌词栏又会继续隐藏任务栏

**Comment by ChanpleCai** [comment]
有截图么，具体歌词栏的位置？

**Comment by ChanpleCai** [comment]
稍微看了下，网易云音乐的歌词窗体是可以特殊处理的 。只不过，有个问题就是，有时会任务栏会遮挡歌词栏。话说你是怎么让歌词栏附加在任务栏上的？

**Comment by vcup** [comment]
![image](https://user-images.githubusercontent.com/53596976/163539724-93f80592-b471-4707-9e2b-35554eb9b5eb.png)

**Comment by vcup** [comment]
那个歌词栏确实是不会隐藏，但如果把桌面的所有窗口都隐藏就会开始隐藏任务栏

**Comment by vcup** [comment]
其实就只是拖拽到任务栏的位置而已，没有什么特别的

**Comment by ChanpleCai** [comment]
好，我知道怎么弄了

**Comment by ChanpleCai** [comment]
试试这个 [v1.4.4](https://github.com/ChanpleCai/SmartTaskbar/releases/download/v1.4.4/SmartTaskbar_Setup.exe)
