### ISSUE TITLE
希望能添加有最大化的时候，使用小图标的选项。感谢

### ISSUE THREAD

**Issue by heartacker** [ChanpleCai/SmartTaskbar#12]
一直在隐藏感觉没有了效率。
但是如果可以有最大化的时候使用小任务栏按钮的话就好了。感谢啦。

**Comment by ChanpleCai** [comment]
这个试过了，新版win10刚刚禁用了相关API；我一开始也是想做成这样，但是失败了。才改成隐藏任务栏的。如果有控制任务栏图标大小的办法，请告知。

**Comment by ChanpleCai** [comment]
v1.1.7已添加改功能
