### ISSUE TITLE
有两台显示器 ，一个显示器上的窗口会影响另一个显示器上的任务栏

### ISSUE THREAD

**Issue by fortystory** [ChanpleCai/SmartTaskbar#13]

**Comment by ChanpleCai** [comment]
这个是一个已知bug，bug的原因在于windows没有提供API可以分别更改两个任务栏。你可以手动设置自动隐藏或显示任务栏试试看，会发现两个任务栏的状态是同时更改的。因为没办法对每个显示器的任务栏分别控制，所以做窗口所在桌面的判断显得多余了。

**Comment by fortystory** [comment]
多谢解答

**Comment by ChanpleCai** [comment]
新的智能模式不会有这个问题了

**Comment by ChanpleCai** [comment]
新版本绕开了这个问题。
