### ISSUE TITLE
能不能增加一个在桌面下自动隐藏任务栏的功能？

### ISSUE THREAD

**Issue by SteveYu000** [ChanpleCai/SmartTaskbar#132]
就是当没有窗口在前端显示时（只有桌面），自动隐藏任务栏。
另外，添加一个白名单，当某些窗口在桌面显示时仍然隐藏任务栏，比如腾讯QQ的初始窗口，以及一些桌面小组件和悬浮窗。

**Comment by 1353604736** [comment]
那你不如直接使用win系统自带自动隐藏任务栏
