### ISSUE TITLE
最大化后最小化再最大化任务栏显示问题

### ISSUE THREAD

**Issue by fortystory** [ChanpleCai/SmartTaskbar#15]
最大化的窗口最小化后点击任务栏中一个最大化的窗口任务栏没有隐藏

以资源管理器为例

<table>
	<tr>
		<td>1</td>
		<td>窗口最大化后</td>
		<td>任务栏隐藏</td>
	</tr>
	<tr>
		<td>2</td>
		<td>点击最小化按钮</td>
		<td>任务栏显示</td>
	</tr>
	<tr>
		<td>3</td>
		<td>点击任务栏资源管理器图标</td>	
		<td>任务栏显示</td>
	</tr>
	<tr >
		<td  rowspan="2">4</td>
		<td>点击其他图标或"显示隐藏的图标"箭头图标</td>
		<td rowspan="2">任务栏隐藏</td>
	</tr>
	<tr>
		<td>或用`Alt-Tab`切换一个最大化的窗口</td>
	</tr>
</table>

**Comment by ChanpleCai** [comment]
这个是功能，只有鼠标移开任务栏，任务栏状态才会改变。你再试试，这个之前有写在ReadMe里面，后面有一次更新删掉了。

**Comment by fortystory** [comment]
多谢解答  谢谢
