### ISSUE TITLE
存在最大化窗口但焦点在非最大化窗口上判断

### ISSUE THREAD

**Issue by RichieChow** [ChanpleCai/SmartTaskbar#16]
存在最大化窗口但焦点在非最大化窗口上，个人认为此时显示任务栏/使用正常图标比较好（或者给个切换的选项

**Comment by ChanpleCai** [comment]
这个我很早之前试过，首先比如右键菜单，这时候符合条件，即存在最大化窗口，但焦点在非最大化窗口上；此时改变任务栏状态会导致，UI刷新，进而引起右键菜单被刷没掉。导致永远无法使用右键菜单功能。其次，chrome窗体最大化的时候，不会触发聚焦窗体改变事件，该方法会在chrome浏览器上失效。然后开始菜单，alt+tab浏览任务，等等一些操作都会触发异常。想法很美好，实现起来非常糟糕，所以我放弃了这个方法。如果后续有更好的办法解决，我会加入这个功能。

**Comment by ChanpleCai** [comment]
已经实现
