### ISSUE TITLE
在win10多桌面环境下，如果chrome最大化切换桌面时会自动切换回原来的桌面

### ISSUE THREAD

**Issue by kijhtybbu** [ChanpleCai/SmartTaskbar#19]
在win10多桌面环境下，如果chrome最大化时切换桌面会自动切换回原来的桌面

chrome68 ,其他软件（如IE）最大化时不会出现这个问题。

**Comment by ChanpleCai** [comment]
我也天天用的Chrome 68， 没有遇到过这种情况。你能详细描述一下触发的方式么，比如开了几个虚拟桌面，win10的版本，是否只有chrome 一个最大化的窗体，chrome是在哪一个虚拟桌面；最大化时是怎么切换的桌面。用alt+tab还是ctrl+win+->还是用四指滚动；我看看能不能复现，好吧。
这个bug，可能是因为更改任务栏状态引起的。

**Comment by kijhtybbu** [comment]
windows 10 家庭版
版本号1803  
操作系统版本 17134.191
两个虚拟桌面，切换方式无论什么都会触发bug

过程我详细研究了一下，发现只要是chrome在两个桌面都打开窗口，其中一个如果是最大化，那么bug就会产生（会自动切换到有最大化窗口的那个虚拟桌面）。如果chrome只在一个桌面或者两个桌面的chrome都是最大化或都不是最大化，不会有bug。

这个bug只会出现‘智能’模式下

**Comment by ChanpleCai** [comment]
卧槽，还真的；

**Comment by ChanpleCai** [comment]
应该是Chrome在响应完任务栏改变事件后，做了什么设置窗体聚焦的动作。

**Comment by kijhtybbu** [comment]
恩，昨晚我跟踪了一下你的代码， 发现这问题了

**Comment by ChanpleCai** [comment]
Chrome 69 bug依然存在

**Comment by ChanpleCai** [comment]
新版本绕开了这个问题
