### ISSUE TITLE
自适应模式 、智能模式  问题请求解决

### ISSUE THREAD

**Issue by nonomal** [ChanpleCai/SmartTaskbar#23]
Win10最新版 
1、 当我的任务栏使用  小任务栏 ，我用自适应模式，发现每次 任务栏无缘无故变为 大任务栏 ，希望能兼容下   默认小任务栏的情况
2、如果我不用  自适应， 智能 的话，能确保一直是小任务栏 ，但扩展屏的的时候，扩展屏不能满屏，下面还是有任务栏（不一定总出现，概率问题出现，特别电脑卡的时候特容易出现）
所以这个很纠结

**Comment by ChanpleCai** [comment]
1. 自适应就是 默认变成大的，然后有全屏变成小的；->这个模式就是：有窗体最大化时使用小任务栏图标，没有的时候使用大任务栏图标
2. 第二个是win10 的bug；无解TT

**Comment by ChanpleCai** [comment]
Bug fixed
