### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by CyshallChan** [ChanpleCai/SmartTaskbar#26]
首先表示对开发者的感谢！

其次就是问题：
软件使用的“智能”模式，然后任务栏使用的“小任务栏按钮”，每次重启或者鼠标点击软件的托盘图标都会使任务栏图标变成正常大小，请问这方面可以改进一下吗？

**Comment by ChanpleCai** [comment]
具体怎么触发的，描述一下；我排查一下看看

**Comment by ChanpleCai** [comment]
可能是配置没有正确存储，你去掉再重新打勾试试；我这边排查一下代码

**Comment by CyshallChan** [comment]
> 具体怎么触发的，描述一下；我排查一下看看

![image](https://user-images.githubusercontent.com/22564041/46640975-9680d980-cba1-11e8-962a-20b1b04e229d.png)
如上图，我设置的“使用小任务栏图标”；
右键软件托盘图标，任务栏图标大小就会自动变成默认的以及电脑重启后，软件自动启动的时候任务栏图标大小也会变成默认的。

**Comment by ChanpleCai** [comment]
你说的意思是指程序的设置掩盖了系统的设置么？

**Comment by ChanpleCai** [comment]
> 
> 
> > 你说的意思是指程序的设置掩盖了系统的设置么？
> 
> https://1drv.ms/v/s!Av4D8-3G0tnBjNQxRuk7d2-4IgEmuA
> 我录了个视频，你看看呢。

- - 打不开，哈哈；我大概知道你什么意思了

**Comment by CyshallChan** [comment]
> > > 你说的意思是指程序的设置掩盖了系统的设置么？
> > 
> > 
> > https://1drv.ms/v/s!Av4D8-3G0tnBjNQxRuk7d2-4IgEmuA
> > 我录了个视频，你看看呢。
> 
> * * 打不开，哈哈；我大概知道你什么意思了

知道就好，知道就好。

**Comment by ChanpleCai** [comment]
现在小按钮设置独立于自适应模式，小按钮仅显示当前任务栏的状态。
