### ISSUE TITLE
1.19版容易导致win10左下角的开始图标消失。

### ISSUE THREAD

**Issue by ryan1123** [ChanpleCai/SmartTaskbar#28]
1.19版容易导致win10左下角的开始图标消失。

**Comment by ChanpleCai** [comment]
开始图标消失？》》怎么出现的？

**Comment by ChanpleCai** [comment]
什么版本的win10我看看能不能复现

**Comment by ryan1123** [comment]
> 什么版本的win10我看看能不能复现

win10专业版 17763.55 
同时 ，开机启动有：WGestures,listary,quicklook,Windynamicdesktop,f.lux

一般就是某个软件全屏最大化后，一定几率出现开始图标消失

**Comment by ChanpleCai** [comment]
是指的win图标消失么

**Comment by ryan1123** [comment]
> 是指的win图标消失么

是的。

**Comment by ChanpleCai** [comment]
如果您能给出 具体全屏的软件和复现的方式（最好是能百分百复现的方式）包括可能相关的是否开启多个显示器，是否使用了其他修改任务栏的软件（包括任务栏上显示信息，修改任务栏开始菜单等各种插件），是否使用了多个桌面，等等。我这边才有可能找到确定的问题根源。目前是没有办法复现···

**Comment by ryan1123** [comment]
> 如果您能给出 具体全屏的软件和复现的方式（最好是能百分百复现的方式）包括可能相关的是否开启多个显示器，是否使用了其他修改任务栏的软件（包括任务栏上显示信息，修改任务栏开始菜单等各种插件），是否使用了多个桌面，等等。我这边才有可能找到确定的问题根源。目前是没有办法复现···

好的，我再试试

**Comment by ryan1123** [comment]
> 如果您能给出 具体全屏的软件和复现的方式（最好是能百分百复现的方式）包括可能相关的是否开启多个显示器，是否使用了其他修改任务栏的软件（包括任务栏上显示信息，修改任务栏开始菜单等各种插件），是否使用了多个桌面，等等。我这边才有可能找到确定的问题根源。目前是没有办法复现···

我试了，浏览器从最大化到最小化时出现。我开了多个win10虚拟的桌面。不知道是不是这个问题。您可以开下试试，不是每次就出现，我这也是刚才突然就出现这种情况了。

**Comment by ChanpleCai** [comment]
> 
> 
> > 如果您能给出 具体全屏的软件和复现的方式（最好是能百分百复现的方式）包括可能相关的是否开启多个显示器，是否使用了其他修改任务栏的软件（包括任务栏上显示信息，修改任务栏开始菜单等各种插件），是否使用了多个桌面，等等。我这边才有可能找到确定的问题根源。目前是没有办法复现···
> 
> 我试了，浏览器从最大化到最小化时出现。我开了多个win10虚拟的桌面。不知道是不是这个问题。您可以开下试试，不是每次就出现，我这也是刚才突然就出现这种情况了。

什么浏览器，鼠标点击最大化最小化是么？

**Comment by ryan1123** [comment]
> 鼠标点击最大化最小化是么？

谷歌浏览器。鼠标点击最大化最小化。

**Comment by ChanpleCai** [comment]
> 
> 
> > 鼠标点击最大化最小化是么？
> 
> 谷歌浏览器。鼠标点击最大化最小化。

没有复现；；；我在Chrome 70.0.3538.77，Win10 17763.55，尝试多种最大化最小化的方式，包括快捷点，鼠标双击顶栏，鼠标点击右上角最大化最小化图标，双击任务栏按钮；同时在虚拟桌面开启Chrome等方式。都没有复现成功。在找到真正原因之前这个问题只能暂时搁置了，兄弟

**Comment by ChanpleCai** [comment]
开始图标消失 是win10 1809的bug

**Comment by ChanpleCai** [comment]
确定是win10bug
