### ISSUE TITLE
欧路词典:最大化后假死

### ISSUE THREAD

**Issue by qiexxii** [ChanpleCai/SmartTaskbar#29]
Version: 1.1.9
Platform: Windows 10 Pro 1803
Description: 

1. 欧路词典 已启动， SmartTaskbar 未启动；
2. 将 欧路词典 最大化；
3. 启动 SmartTaskbar；
4. 欧路词典 假死，变成下面截图的样子。

此bug有点难复现，只是极小概率会出现。

----
Screenshot:

![image](https://user-images.githubusercontent.com/16456434/48670902-2596ef00-eb5b-11e8-9698-4a19a571d5ce.png)

**Comment by ChanpleCai** [comment]
那这就是，它这个软件的问题了。。。

**Comment by ChanpleCai** [comment]
非本软件问题，后续加入黑白名单解决
