### ISSUE TITLE
新功能提议

### ISSUE THREAD

**Issue by Tomotoes** [ChanpleCai/SmartTaskbar#31]
当显示任务栏时,增加 任务栏透明化,或者磨砂化 功能.

**Comment by ChanpleCai** [comment]
好的~

**Comment by ChanpleCai** [comment]
可以去试试使用 https://github.com/TranslucentTB/TranslucentTB 他们的软件对这个功能支持更好一些。我之前加入这个功能，效果还可以，只是一直要调用接口刷新UI，开销比较大。再三考虑，最后移除了。
