### ISSUE TITLE
问题求助

### ISSUE THREAD

**Issue by yu037991** [ChanpleCai/SmartTaskbar#33]
开着软媒时间，然后打开Chrome浏览器，智能任务栏隐藏之后，再唤出任务栏会发现，右下角任务栏的东西都找不到了。是有冲突还是Bug啊？怎么解决呢？

**Comment by ChanpleCai** [comment]
是软媒时间不见了么? 那应该是它软件没有实时检测任务栏的位置...所以任务栏跑了它还藏着, 这个我没办法帮你修复哦~

**Comment by yu037991** [comment]
不是软媒时间不见了，开了软媒和智能任务栏右下角的东西都找不到了
[image](https://user-images.githubusercontent.com/30470617/54253931-7ad49180-458c-11e9-8aeb-81f08b82da14.png)
不开软媒时间，只开智能任务栏是这样的
![image](https://user-images.githubusercontent.com/30470617/54253967-b707f200-458c-11e9-8468-6592a8d8f52c.png)

**Comment by yu037991** [comment]
开了软媒时间和智能任务栏
![image](https://user-images.githubusercontent.com/30470617/54254024-0d753080-458d-11e9-973d-e61bb2d21278.png)

**Comment by ChanpleCai** [comment]
感觉应该是 软媒时间把通知区域的父窗口改成它自己了,,, 所以不跟着任务栏一起走了. 你试一下看如果只设置自动隐藏任务栏, 会不会出现这个问题

**Comment by yu037991** [comment]
> 感觉应该是 软媒时间把通知区域的父窗口改成它自己了,,, 所以不跟着任务栏一起走了. 你试一下看如果只设置自动隐藏任务栏, 会不会出现这个问题

还是会出现这个问题。。。

**Comment by ChanpleCai** [comment]
那就是它这个软件的问题了, 自动隐藏是windows 自带的功能; 理论上软件需要适配操作系统~

**Comment by ChanpleCai** [comment]
和SmartTaskbar无关
