### ISSUE TITLE
Potplay

### ISSUE THREAD

**Issue by JankingHuang** [ChanpleCai/SmartTaskbar#40]
对于PotPlay这个软件最大化时，鼠标移动到隐藏任务栏的地方。不会自动弹出任务栏。按win键弹出菜单的时候采用出现任务栏

**Comment by ChanpleCai** [comment]
- - 这个是任务栏的bug, 你可以试一下手动设置自动隐藏任务栏; 然后会发现还是一样的问题, 还有类似的一堆软件有这个问题...

**Comment by ChanpleCai** [comment]
> 
> 
>     * * 这个是任务栏的bug, 你可以试一下手动设置自动隐藏任务栏; 然后会发现还是一样的问题, 还有类似的一堆软件有这个问题...

其实应该是, 软件写得不规范 ...

**Comment by JankingHuang** [comment]
谢谢
