### ISSUE TITLE
Windows side by side do not hide taskbar

### ISSUE THREAD

**Issue by gilbertosilvaoliv** [ChanpleCai/SmartTaskbar#41]
When I put windows side by side (split option) do not hide taskbar.

Would it be possible to detect this scenario as well and hide the taskbar?

How is:

![How is](https://user-images.githubusercontent.com/829849/57499371-da61cb80-72b5-11e9-80a2-920bbf9b8153.jpg)

How Should be:

![How should be](https://user-images.githubusercontent.com/829849/57499370-da61cb80-72b5-11e9-8e17-17f671c0852b.jpg)

**Comment by ChanpleCai** [comment]
working on it`

**Comment by ChanpleCai** [comment]
The new version bypasses this problem.
