### ISSUE TITLE
win7为什么没有效果

### ISSUE THREAD

**Issue by YourXin** [ChanpleCai/SmartTaskbar#43]
最大化和最小化，win7没有反应，

**Comment by ChanpleCai** [comment]
理论上, win7也是支持的哦. 不过我没有测试过. 后续也不会继续做兼容了==

**Comment by YourXin** [comment]
> 理论上, win7也是支持的哦. 不过我没有测试过. 后续也不会继续做兼容了==

好吧 。有点可惜
