### ISSUE TITLE
Maximize window in new windows workspace like MacOS

### ISSUE THREAD

**Issue by zhangzw16** [ChanpleCai/SmartTaskbar#44]
Hope to add a new feature that when maximizing a window,  it moves to a new windows workspace and hide the taskbar automatically like MacOS.

Moreover, users can config the setting to choose the behavior they want.

**Comment by ChanpleCai** [comment]
Good idea, I can try to see if it can be achieved~

**Comment by ChanpleCai** [comment]
Difficult to implement.
