### ISSUE TITLE
希望能解决在与DisplayFusion同时运行时任务栏无法自动显示的问题

### ISSUE THREAD

**Issue by changlianze** [ChanpleCai/SmartTaskbar#47]
在与DisplayFusion同时运行时，任务栏可以在窗口最大化时自动隐藏，但将鼠标移到任务栏位置时不会自动显示。这个问题在使用单一显示器和双显示器时都存在，而且在单一显示器使用且退出DisplayFusion后消失。希望能检查一下并修复，支持国产优秀软件！

**Comment by ChanpleCai** [comment]
我买一个DisplayFusion玩一下试试(￣▽￣)"

**Comment by changlianze** [comment]
感谢回复！ 常泽 邮箱：changlianze@gmail.com 签名由 网易邮箱大师 定制 在2019年07月06日 08:02，Chanple 写道： 我买一个DisplayFusion玩一下试试(￣▽￣)" — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ChanpleCai** [comment]
DisplayFusion的多任务栏模式其实是 它自己写的假任务栏, 然后替换了真的任务栏; 所以导致SmartTaskbar失效了.

**Comment by changlianze** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        收到，感谢回复！个人现在用DisplayFusion主要是需要监视器褪化功能，但在软甲运行的情况下即使是不启用DisplayFusion的任务栏管理，SmartTaskbar也会失效，也就是说软甲只要运行就替换了Windows的任务栏？那这个是否有办法能解决呢？
        
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                changlianze
                            
                    
                        
                            
                                    changlianze@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年7月8日 13:53，Chanple<notifications@github.com> 写道： 


DisplayFusion的多任务栏模式其实是 它自己写的假任务栏, 然后替换了真的任务栏; 所以导致SmartTaskbar失效了.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
