### ISSUE TITLE
Number of features in the app from the Windows Store

### ISSUE THREAD

**Issue by redview13** [ChanpleCai/SmartTaskbar#49]
Bought the app in the Windows Store. Why is it less functional? In the examples I see more functionality ((

**On my PC**
<img src="https://c5heiq.db.files.1drv.com/y4mBdwIoxHV0yQo6aBVPh6T33Drj9l0rhG75M-Z_spFKJNY7M7orgLYRGjhDc-CWXv0lP4yHH4HZlZ1-0tB22pKHLBobZulurH2vmyqOze7nktQpPr7cxywLMJHxayHwzIOrthScDR6GVmMV2K5Zgjpz_zuTxIHSQNpHdMGziGX5v30fUCLo1Dm0OM2S84eAr3QA5yl-miUv_PvxMs4GMvkBA?width=239&height=169&cropmode=none" width="239" height="169" />

**You have examples**
<img src="https://c5hfiq.db.files.1drv.com/y4mRQXcjhF9KgC4Gb8MfZFNQlZaU1VALx7HEdZ9SQqcs86wzcHvH1P9fyNsPxCR0KQs7Jxzz5XJn0-hfT9DCuWJvBsu0agEhWtx3PYT_5YLze62AhIs3tV1PQ7uulNX-vaawqcDR_MfyoC8mbCYpFp3SNu-n0n4Zoe8moGqIID99S1lGkrnnNZRru6tKQLZL3PkNE88cwebUOd1muFf5MBfhg?width=215&height=237&cropmode=none" width="215" height="237" />

**Comment by ChanpleCai** [comment]
The UWP does not allow direct manipulation of the (real) registry, but currently I only know how to control the size of the taskbar icon through the registry.

 https://stackoverflow.com/questions/34694059/read-write-registery-key-file-in-uwp

 https://stackoverflow.com/questions/48899692/how-to-access-registry-key-in-a-uwp-app

App using Brokered Components will not pass certification.
