### ISSUE TITLE
QQ或微信有消息提示时可不自动显示任务栏

### ISSUE THREAD

**Issue by tssh1984** [ChanpleCai/SmartTaskbar#50]
QQ或微信有新消息时，任务栏会自动显示，希望可以不自动显示。
因为我是将任务栏靠右放置，这样子就挡住了之前窗口的关闭按钮。

**Comment by ChanpleCai** [comment]
嗯嗯, 这个是因为腾讯系软件的最大化方式导致的问题; 暂时没有更好的办法处理, 我还在想办法

**Comment by tssh1984** [comment]
哈哈，原来是没有用这个工具的时候，把任务栏放在右侧，以使可用屏幕更高，其实用了这个之后，任务栏放在底部就可以满足我的要求了。👍👍👍👍👍👍👍

**Comment by ChanpleCai** [comment]
发现之前回复错了。这个是任务栏flash闪动。暂时还不知道怎么关闭，有一种办法是你可以在微信或者qq设置不提示消息，哈哈。
