### ISSUE TITLE
奇怪的问题

### ISSUE THREAD

**Issue by Windowscoder** [ChanpleCai/SmartTaskbar#54]
在两台pc机上使用，其中一台过度很流畅，另一台有桌面切换为全屏模式后，任务栏还会闪烁一下。两台电脑的win10版本一样，希望作者解答下，谢谢！

**Comment by ChanpleCai** [comment]
首先win10的任务栏写的很烂，本身就会各种刷新bug；另外这个好像跟电脑的配置，比如固态，显卡，CPU有关系，具体关系不清楚；任务栏是异步更新的，而且优先级不是很高，所以偶尔会出现闪烁，在配置差的电脑上更明显一点

**Comment by Windowscoder** [comment]
感谢




| |
18622070636
|
|
邮箱：18622070636@163.com
|

Signature is customized by Netease Mail Master

在2020年01月21日 10:11，Chanple 写道：

首先win10的任务栏写的很烂，本身就会各种刷新bug；另外这个好像跟电脑的配置，比如固态，显卡，CPU有关系，具体关系不清楚；任务栏是异步更新的，而且优先级不是很高，所以偶尔会出现闪烁，在配置差的电脑上更明显一点
