### ISSUE TITLE
Taskbar flickering when window is maximized

### ISSUE THREAD

**Issue by st-den** [ChanpleCai/SmartTaskbar#56]
Hey! Thanks for this project.

So the problem is that taskbar/window is flickering on window maximize. Same with Animation on/off. Is it even possible to make it smooth?

Tried to capture this behavior in the gif below. 

![gif](https://user-images.githubusercontent.com/46577620/77368788-ac6a6600-6d65-11ea-9105-96006416300d.gif)

**Comment by ChanpleCai** [comment]
This problem is related to the refresh method of the windows system UI. I have no way to fix it,  unless Microsoft rewrites the taskbar in the future.

**Comment by ChanpleCai** [comment]
Microsoft really rewrote the taskbar, but the problem is still.
