### ISSUE TITLE
任务栏闪一下

### ISSUE THREAD

**Issue by Flora-air** [ChanpleCai/SmartTaskbar#58]
隐藏任务栏的时候，任务栏会闪一下
因为反馈不能发截图或者视频
安全启动之后 录的一段视频上传到了度盘
 希望开发者有空看一下
链接：https://pan.baidu.com/s/1jZpRuOoGvGadyMijzeGxRQ 
提取码：dr6c

**Comment by ChanpleCai** [comment]
这个是windowsUI的刷新机制导致的。暂时没有办法，等我摸清楚它的原理（鸽了），看看有没有方法不让它这样闪。

**Comment by yaohappiness** [comment]
Windows 的 bug 真是随机复现☹️
