### ISSUE TITLE
建议功能：【当任务栏被占满时自动增加一行】

### ISSUE THREAD

**Issue by loktindyi** [ChanpleCai/SmartTaskbar#63]
我不习惯大图标始终合并，更喜欢小图标展开
于是我遇到了问题：大部分时间我的任务栏够用，
但偶尔处理很多任务时，我就需要两行任务栏来容纳它们
我需要在这时有程序帮我做这件事
即：【当任务栏被占满时自动增加一行】

**Comment by ChanpleCai** [comment]
判断何时需要两个任务栏是个麻烦；并且移动任务栏需要先解锁任务栏锁定，然后模拟鼠标拉动，然后再次锁定任务栏才可以； 有相关的autohotkey脚本可以改造一下，但是没有对应的系统API实现对应的功能。

**Comment by XiaoXin1900** [comment]
> 判断何时需要两行任务栏是个麻烦；并且移动任务栏需要先解锁任务栏锁定，然后模拟鼠标拉动，然后再次锁定任务栏才可以； 有相关的autohotkey脚本可以改造一下，但是没有对应的系统API实现对应的功能。

当有全屏窗口时，让任务栏弹出，此时任务栏为空(注：本人为侧边栏显示），这个是bug还是什么原因呢？

**Comment by loktindyi** [comment]
我从来没有遇到过这种情况，猜测是windows的奇妙bug。他总会有一些奇奇怪怪的bug...
比如：我从开始菜单点击任何文件夹后 ，文件夹都会从后台打开，而开始菜单不会自动退出。这个问题困扰我很久，最终我通过卸载了部分更新恢复正常，而后重新安装更新也没有再出现问题。

**Comment by loktindyi** [comment]
> > 判断何时需要两行任务栏是个麻烦；并且移动任务栏需要先解锁任务栏锁定，然后模拟鼠标拉动，然后再次锁定任务栏才可以； 有相关的autohotkey脚本可以改造一下，但是没有对应的系统API实现对应的功能。
> 
> 当有全屏窗口时，让任务栏弹出，此时任务栏为空(注：本人为侧边栏显示），这个是bug还是什么原因呢？

我从来没有遇到过这种情况，猜测是windows的奇妙bug。他总会有一些奇奇怪怪的bug...
比如：我从开始菜单点击任何文件夹后 ，文件夹都会从后台打开，而开始菜单不会自动退出。这个问题困扰我很久，最终我通过卸载了部分更新恢复正常，而后重新安装更新也没有再出现问题。

**Comment by ChanpleCai** [comment]
实现难度过大暂不考虑。
