### ISSUE TITLE
Cant find my post and reply?

### ISSUE THREAD

**Issue by Ansu72** [ChanpleCai/SmartTaskbar#66]
Issue:
Hi, sorry for taking up some space. I had an Issue note here which i posted some days ago, and someone replied but i didnt have the time to read it fully at that time...and then...i forgot about it...Now i cant find neither issue not neither as resolved nor unresolved.
Ok you get the idea, how and where does happy, or unhappy,  issue notes go after they have lived a purposeful  Life? Or not....

She said something about having the same windows 10 build as i did, which is 19041.572, The issue i had was that the start field Cortana and the timeline neither is responding to Trancelucent TB.
ISSUE END.

Any pointers would be appreciated, ive been fiddling with this for quite some time now and its getting to the point where it starts to have its own personality and i don't want to start talking to the damn thing maybe except for...."Hey M.F. either you start working like Yesterday or your ejected from this system a** first, as Light.

Last part was just my dry humor, sorry, your right it doesn't belong here...although it too is a kind of dry place too :o) Now your thinking "If you can both ask And answer your Own questions then how about you do that with you issue too."  but it wasn't Real you see... :) so once again i must interject that it was just my terribly dry and bad Swedish humor, except I'm laughing...a bit.., ,

SMIIIiiiLE!!

Best regards,

Ansu

**Comment by ChanpleCai** [comment]
19041.572? Trancelucent TB ? Maybe what you are looking for is this: [https://github.com/TranslucentTB/TranslucentTB/issues/340 ](url)

**Comment by ChanpleCai** [comment]
Irrelevant.
