### ISSUE TITLE
Frozen / Blank Google Chrome upon switching virtual desktop

### ISSUE THREAD

**Issue by lenowng** [ChanpleCai/SmartTaskbar#68]
Behavior: Google Chrome browsed page will be frozen or left blank after switching away to another virtual desktop, then switch back using gestures but application resume fine when opening new tab or refreshing the page.

**Comment by ChanpleCai** [comment]
which version of Chrome it is?

**Comment by lenowng** [comment]
Am running on `Version 86.0.4240.111 (Official Build) (64-bit)`

**Comment by ChanpleCai** [comment]
The problem with Chrome and the virtual desktop should be a Chrome bug, and SmartTaskbar happened to trigger it. I will try to avoid this.

**Comment by lenowng** [comment]
Thanks! Anyway, SmartTaskbar froze slack too if that helps but work fine if I kill SmartTaskbar process. (not sure if it's related)

**Comment by ChanpleCai** [comment]
The new version bypasses this problem.
