### ISSUE TITLE
反馈两个问题

### ISSUE THREAD

**Issue by candyl6** [ChanpleCai/SmartTaskbar#7]
1.可以安装到其他盘吗？
2.我用的UC浏览器，运行一段时间后，鼠标移动到任务栏，任务栏不会自动弹出（不知道是不是个例）

**Comment by ChanpleCai** [comment]
哈，因为这个程序占用很小，只有1.81MB；并且需要开机启动，出于加载速度的考虑，就没有提供安装到其他盘的选项；如果要安装到其他盘，你可以再程序没有运行的时候，把C:\Program Files\SmartTaskbar复制到需要的目录，然后win+r 运行shell:startup，重新定向一下SmartTaskbar的快捷方式链接目标就可以。

**Comment by ChanpleCai** [comment]
有些应用如网易云音乐，YY等，在任务栏为自动隐藏模式时，最大化会彻底隐藏任务栏；你可以手动设置任务栏为自动隐藏状态；然后查看是否任务栏被彻底隐藏，如果此时任务栏也是无法弹出，就说明是这个软件在设计时没有考虑任务栏为自动隐藏模式的情况。
这个不是SmartTaskbar的bug，而是它们程序设计的问题~

**Comment by ChanpleCai** [comment]
下个版本我会把安装目录，设置为可选的~

**Comment by candyl6** [comment]
我试试是不是UC的问题
