### ISSUE TITLE
和滴答清单的桌面任务列表插件有兼容问题

### ISSUE THREAD

**Issue by Jayonli** [ChanpleCai/SmartTaskbar#70]
![image](https://user-images.githubusercontent.com/73680878/98455460-eb8de000-21ab-11eb-97e1-da5d5baae0a7.png)，在智能模式或者自适应的模式下，就会出现这种情况。

**Comment by ChanpleCai** [comment]
emm, 但是这个不是SmartTaskbar的锅啊。╮(╯▽╰)╭

**Comment by ChanpleCai** [comment]
你可以给他们官方反馈一下这个bug。应该不难改。

**Comment by Jayonli** [comment]
> 你可以给他们官方反馈一下这个bug。应该不难改。

嗯嗯，谢谢
