### ISSUE TITLE
调出任务栏导致软件功能失灵

### ISSUE THREAD

**Issue by LeuJue** [ChanpleCai/SmartTaskbar#72]
在保持一个窗口最大化的前提下，鼠标激活任务栏就不能再自动隐藏了

**Comment by ChanpleCai** [comment]
啥意思，能在详细描述一下么

**Comment by LeuJue** [comment]
> 啥意思，能在详细描述一下么

在提出反馈的时候是这样一种情况：浏览器最大化显示，任务栏隐藏→鼠标滑到底部→任务栏出现→点击任务栏→鼠标移回浏览器窗口→任务栏不消失。
但是，我今天突然发现又可以正常出现和隐藏了😂😂

**Comment by ChanpleCai** [comment]
> 
> 
> > 啥意思，能在详细描述一下么
> 
> 在提出反馈的时候是这样一种情况：浏览器最大化显示，任务栏隐藏→鼠标滑到底部→任务栏出现→点击任务栏→鼠标移回浏览器窗口→任务栏不消失。
> 但是，我今天突然发现又可以正常出现和隐藏了😂😂

这是win10 的bug。

**Comment by LeuJue** [comment]
> > > 啥意思，能在详细描述一下么
> > 
> > 
> > 在提出反馈的时候是这样一种情况：浏览器最大化显示，任务栏隐藏→鼠标滑到底部→任务栏出现→点击任务栏→鼠标移回浏览器窗口→任务栏不消失。
> > 但是，我今天突然发现又可以正常出现和隐藏了😂😂
> 
> 这是win10 的bug


> > > 啥意思，能在详细描述一下么
> > 
> > 
> > 在提出反馈的时候是这样一种情况：浏览器最大化显示，任务栏隐藏→鼠标滑到底部→任务栏出现→点击任务栏→鼠标移回浏览器窗口→任务栏不消失。
> > 但是，我今天突然发现又可以正常出现和隐藏了😂😂
> 
> 这是win10 的bug。

OK
