### ISSUE TITLE
SmartTaskbar会导致桌面图标删除异常

### ISSUE THREAD

**Issue by cliuyang** [ChanpleCai/SmartTaskbar#76]
删除桌面上的文件 ，打开一个应用后再关闭，删除文件还在桌面，无法打开或删除，刷新后图标消失。

关闭SmartTaskBar后上述情形消失。

SmartTaskBar会根据情况调整图标的位置，我估计就是这里导致的异常。

我的win10版本为：20h2
任务栏设置在左侧，SmartTaskBar的设置为动画，智能。

（我看到作者最近一直在更新代码，但是一直没有发布新版本，还是18年的旧版本，什么时候打算发布新版本呀）

**Comment by jklinCN** [comment]
同有这个情况。并且在打开SmartTaskBar后，当我从最大化的chrome切换回桌面时，桌面的图标会重新调整一下，希望作者抽空可以解决一下

**Comment by ChanpleCai** [comment]
这是windows10的bug啊。之前尝试了很多新方法，都没有办法完全解决，所以一直就没发新版本。
