### ISSUE TITLE
继续反馈个奇怪的问题

### ISSUE THREAD

**Issue by candyl6** [ChanpleCai/SmartTaskbar#8]
我的桌面有7x10个图标，打开我的电脑，最大化之后，状态栏隐藏，然后再最小化或者还原窗口，桌面图标会自动按照6行图标来排列，刷新一下才会变成7x10的排列。系统版本win10 LTSB，64位

**Comment by ChanpleCai** [comment]
这个是正常的==你可以手动设置任务栏状态试试看。你把桌面分成两个部分，任务栏和放图标的区域，当任务栏隐藏时，图标的显示区域就变大了，就会自适应的变大；如果两个布局不一致，就会这样一直跳。。。

**Comment by ChanpleCai** [comment]
windows 这个任务栏的API 说实在的，太多历史遗留问题；这也是为什么，微软自己不开发一个智能隐藏任务栏功能的原因（Linux 和macOS都有这个功能）；我本人的能力也有限，没办法改它；你暂时可以，手动设置一下显示或隐藏状态，把图标调整一下。目前只能这样= =如果你有更好的解决方案的话，欢迎帮忙改进~

**Comment by ChanpleCai** [comment]
windows 这个任务栏的API 说实在的，太多历史遗留问题；这也是为什么，微软自己不开发一个智能隐藏任务栏功能的原因（Linux 和macOS都有这个功能）；我本人的能力也有限，没办法改它；你暂时可以，手动设置一下显示或隐藏状态，把图标调整一下。目前只能这样= =如果你有更好的解决方案的话，欢迎帮忙改进~

**Comment by ChanpleCai** [comment]
每次任务栏状态改变 都会引起其他所有窗体布局刷新 桌面也是一个窗体。后面的机制是比较底层的 改它会引起更多bug。所以我没有对这个问题进行处理

**Comment by candyl6** [comment]
哦哦，好的

**Comment by candyl6** [comment]
@ChanpleCai 还是不对，将软件设置为隐藏也就是不启用智能状态的时候，鼠标移到任务栏位置，任务栏显示，这时候最靠近任务栏的图标会被任务栏遮盖住一小部分，桌面布局不会改变。启用智能状态后，最小化窗体让任务栏显示的时候桌面布局会发生改变，刷新下桌面布局才会正常，就比如桌面图标布局为7x6，智能状态下任务栏显示的时候会将布局改成6x7，但是自动隐藏任务栏模式下任务栏显示的时候不会更改桌面布局。如果这的确是微软的bug的话，作者不妨加一个自动刷新的操作，就是当任务栏显示的时候刷新下桌面（貌似评论不能发图，否则发图就能解释更清楚了）

**Comment by candyl6** [comment]
不好意思，发现确实是微软的问题，我在设置中不停地启用和关闭 “在桌面模式下自动隐藏任务栏”选项的时候发现系统确实会自动更改桌面布局，也就是说，当切换这个选项开关的时候会出现更改桌面布局的问题，作者的这个软件应该就是这个原理吧？但是，当这个选项开启的时候，触发使任务栏显示的时候又不会修改桌面布局，这又是怎么实现的呢？或许作者可以在任务栏显示的时候默认增加一个刷新操作，不知道是不是可以实现，辛苦作者了

**Comment by ChanpleCai** [comment]
这个要再研究一下，它是这样的，有时候会有时候不会，很难搞

**Comment by ChanpleCai** [comment]
在新的自动模式下该问题不再存在
