### ISSUE TITLE
Windows11 窗口缩小时会不断最大化、还原

### ISSUE THREAD

**Issue by LeeLeeee** [ChanpleCai/SmartTaskbar#82]
Windows11 Build 22000.51 中，窗口最大化后还原，窗口会再次自动最大化，然后还原，然后一直循环，只能关闭应用程序

**Comment by bigQY** [comment]
+1

**Comment by ZhizhenZhou** [comment]
+1

**Comment by wcc-yo** [comment]
+1

**Comment by XQLsj99** [comment]
+1 这真的太难受了

**Comment by ZeemanZhang** [comment]
+1

**Comment by shanyan-wcx** [comment]
+1

**Comment by ChanpleCai** [comment]
微软把任务栏重写了。。。

**Comment by wispamulet** [comment]
+1

**Comment by nikoshinigami** [comment]
It actually works  better in last build. Still has problems with snap windows

**Comment by obrobrio2000** [comment]
> It actually works better in last build. Still has problems with snap windows

What exactly are you referring to? I'm on last build too (22000.65) but I didn't notice improvements (still has the same bug that prevents you from minimizing a window, other than the snap windows bug).

**Comment by nikoshinigami** [comment]
You’re right, this is still a problem. But at least the taskbar actually hides, when a window is maximized. That didn’t work on the first build

**Comment by CynicalCloud** [comment]
Just noticed if you minimize a maximized window by actually clicking on the taskbar icon for the indow it seems to work fine, no bug that way, a half workaround until the bug is fixed, if it ever gets fixed that is :)

**Comment by wuyudelan** [comment]
Same problem for 22000.184, hope you can fix it.

**Comment by bzzrak** [comment]
Any updates?...

**Comment by ChanpleCai** [comment]
I just released a version to the Microsoft store. If you find any bugs, please give me feedback.
我刚更新了一个版本到应用商店，可以去下载来试试。

**Comment by obrobrio2000** [comment]
> I just released a version to the Microsoft store. If you find any bugs, please give me feedback. 我刚更新了一个版本到应用商店，可以去下载来试试。

Works well on my end. The only two bugs I encountered are:
1) The taskbar doesn't stay open when going to desktop by minimizing a fullscreen window, the autohide stays on. Doesn't happen instead when going to desktop by minimizing a reduced window.
2) The "taskbar going up" animation is present when hovering but is not present when reducing/minimizing a fullscreen window or when going to the desktop.

I recorded both in this video:
https://user-images.githubusercontent.com/62136803/139773834-cde07bdc-53af-4f56-bbe1-45d653ec934c.mp4

**Comment by ChanpleCai** [comment]
> > I just released a version to the Microsoft store. If you find any bugs, please give me feedback. 我刚更新了一个版本到应用商店，可以去下载来试试。
> 
> Works well on my end. The only two bugs I encountered are:
> 
> 1. The taskbar doesn't stay open when going to desktop by minimizing a fullscreen window, the autohide stays on. Doesn't happen instead when going to desktop by minimizing a reduced window.
> 2. The "taskbar going up" animation is present when hovering but is not present when reducing/minimizing a fullscreen window or when going to the desktop.
> 
> I recorded both in this video:
> 
>  2021_11_02_021419.mp4

I just updated another version and fixed the first bug. The second one seems to be windows' own bug.

**Comment by shanyan-wcx** [comment]
几个bug：
1.在桌面点击开始，任务栏也会隐藏一次。
2.控制中心，消息中心等界面位置下移（微软的问题）。
3.全屏窗口最小化时需要点一下桌面任务栏才会出现。


https://user-images.githubusercontent.com/58252651/139791861-dc5bd037-a0cc-404d-9867-955c1f4038e0.mp4

**Comment by ChanpleCai** [comment]
> 几个bug： 1.在桌面点击开始，任务栏也会隐藏一次。 2.控制中心，消息中心等界面位置下移（微软的问题）。 3.全屏窗口最小化时需要点一下桌面任务栏才会出现。
> 
>  20211102_132229.mp4

第一个问题要hook任务栏才可以屏蔽关闭开始菜单时自动隐藏任务栏的机制，因为要发布到微软商店不好弄就没弄了；
第二个我试试改成点击这些选项的时候把任务栏藏起来？
第三个我看下，修好了就更。

**Comment by obrobrio2000** [comment]
> > > I just released a version to the Microsoft store. If you find any bugs, please give me feedback. 我刚更新了一个版本到应用商店，可以去下载来试试。
> > 
> > 
> > Works well on my end. The only two bugs I encountered are:
> > 
> > 1. The taskbar doesn't stay open when going to desktop by minimizing a fullscreen window, the autohide stays on. Doesn't happen instead when going to desktop by minimizing a reduced window.
> > 2. The "taskbar going up" animation is present when hovering but is not present when reducing/minimizing a fullscreen window or when going to the desktop.
> > 
> > I recorded both in this video:
> > 2021_11_02_021419.mp4
> 
> I just updated another version and fixed the first bug. The second one seems to be windows' own bug.

Thank you! Now it works fine :)
