### ISSUE TITLE
Windows 11 issue

### ISSUE THREAD

**Issue by areebhussain321** [ChanpleCai/SmartTaskbar#85]
Hi, on windows 11.

when you have SmartTaskbar enabled, when in a maximised tab it works! the taskbar goes away. however when you make the tab in a window , it keeps glitching back and forth to maximised and windowed. really glitchy to the point where its unusable until fixed.

Hope it can be fixed for windows 11 as I use this alot. Love this too keep up the work

**Comment by ChanpleCai** [comment]
Windows 11 has rewritten a lot of UI parts. The old API method will cause bugs. I am trying to avoid it with new methods. The basic functions have been implemented, but many new bugs have been created unintentionally. At present, I don't know how long it will take to solve the problem. I am constantly trying.

**Comment by ChanpleCai** [comment]
I just released a version to the Microsoft store. If you find any bugs, please give me feedback.

**Comment by areebhussain321** [comment]
Great! Thank you for everything. Will try it out now

**Comment by areebhussain321** [comment]
Works!!

**Comment by areebhussain321** [comment]
Nevermind. It seems after a bit it just enables ‘Automatically hide the
taskbar’ setting in taskbar settings. So even on desktop or windows mode
after a while the taskbar doesn’t pop up again.

**Comment by ChanpleCai** [comment]
So , the taskbar won't appear by itself?  I will look again and try to fix it in the next few days.

**Comment by areebhussain321** [comment]
Yep. Taskbar just says ‘Ight Imma head out’

No problem, take your time!

**Comment by ChanpleCai** [comment]
It looks like I forgot to show the taskbar when displaying the desktop. Open a few more windows to see if it will work normally, the current function is to hide when there is a window intersecting the taskbar.
I will submit the new version today.
