### ISSUE TITLE
Can you make the tiny line disappear when taskbar is hidden, and the taskbar do not show when you go near it accidentally

### ISSUE THREAD

**Issue by adamlahbib** [ChanpleCai/SmartTaskbar#86]
I love the project. Thanks for making this great tool! I believe I've been looking for somthing like this for a while. I even made this as a suggestion to Windows Feedback Hub, to make the auto hide taskbar feels more like the Mac OS experience. Anyway that tiny line that keeps showing by default from Windows, I guess you can handle that and you should make it only show up when you reach the edge of screen last pixel, make it behave more like the Mac OS. Because with a light theme, and long hours of use it can cause some burns to the screen and thats what makes some users concerned on Reddit mostly.
Anyway I know another tool that can remove that line. They might work together... but it will be a nice option to add in the program to be all in one.

**Comment by ChanpleCai** [comment]
Windows 11 has rewritten a lot of UI parts. The old API method will cause bugs. I am trying to avoid it with new methods. The basic functions have been implemented, but many new bugs have been created unintentionally. At present, I don't know how long it will take to solve the problem. I am constantly trying.

**Comment by ChanpleCai** [comment]
I just released a version to the Microsoft store. If you find any bugs, please give me feedback.

**Comment by adamlahbib** [comment]
Already testing it, it looks great, but does it really cost 60 MB xD to do such function?

**Comment by ChanpleCai** [comment]
The size of the file is large because the Microsoft Store will run the application in a sandbox. In this way, all software dependent dlls must be installed together. So the size becomes larger. Running in the sandbox can ensure that the software does not threaten the system (in theory).

**Comment by ChanpleCai** [comment]
I personally control the CPU overhead as much as possible to the minimum. As for the memory and hard disk size, well, unless I rewrite it in C++ or Rust (I haven't learned it yet).

**Comment by ChanpleCai** [comment]
The CPU overhead is kept as low as possible. As for the memory and hard disk size, well, unless I rewrite it in C++ or Rust (I haven't learned it yet).

**Comment by DinuruSeniya** [comment]
Hi,
I am using the latest version of SmartTaskbar with the latest Windows 11 updates, the issue is still there, once the taskbar goes down, a small white line flashes rapidly. And sometimes the taskbar would come up and go down again before you can click anything. Sometimes the taskbar would never come up at all. I have to force quit SmartTaskbar from the Task Manager and uncheck auto-hide from Settings to get it back. 
P.S : I am also using RoundedTB with SmartTaskbar, maybe that's the issue. But it would be great if you could make both of them work together.
