### ISSUE TITLE
I've been using your app for years now but now it no longer work on windows 11.. can u fix or update the app on either here or ms store pls ?

### ISSUE THREAD

**Issue by thelosttime0601** [ChanpleCai/SmartTaskbar#87]
I've just updated to the latest build of Windows 11 and as soon as I open my app, every tabs and app keep uncontrollably resize

**Comment by ChanpleCai** [comment]
Windows 11 has rewritten a lot of UI parts. The old API method will cause bugs. I am trying to avoid it with new methods. The basic functions have been implemented, but many new bugs have been created unintentionally. At present, I don't know how long it will take to solve the problem. I am constantly trying.

**Comment by ChanpleCai** [comment]
I just released a version to the Microsoft store. If you find any bugs, please give me feedback.
