### ISSUE TITLE
对Bug的处理（白名单）

### ISSUE THREAD

**Issue by ghost** [ChanpleCai/SmartTaskbar#9]
由于windows自带的问题，有些复杂的情况很难处理，可以考虑添加白名单机制，对部分最大化窗口不隐藏，解决这些窗口出现小问题令人不适的情况。。。

**Comment by ChanpleCai** [comment]
嗯嗯，这个我有在尝试，但是开销有点大，要实时比对名单内进程是否运行。还要再研究一下，有没有开销小速度更快的方法；等有空就会加上这个功能的

**Comment by ChanpleCai** [comment]
新版本绕开了这个问题。
