### ISSUE TITLE
在使用开始菜单栏里的搜索功能时，之前的任务栏闪烁问题又会出现

### ISSUE THREAD

**Issue by 123de234** [ChanpleCai/SmartTaskbar#90]

**Comment by ChanpleCai** [comment]
哪个版本的呀？

**Comment by 123de234** [comment]
https://user-images.githubusercontent.com/23733252/139870574-af7d2c35-ed65-4f17-8ccb-96c9503426c8.mp4

**Comment by 123de234** [comment]
关闭startallaback后是这样，在进行搜索时任务栏会自动合并，我认为这样很不自然。

这是开启与关闭智能时的对比：

通常：

https://user-images.githubusercontent.com/23733252/139873430-ff239dd5-4514-4318-bb8c-e3586891e265.mp4

开启软件后：

https://user-images.githubusercontent.com/23733252/139873615-4606be06-806f-4b2e-8c31-162a119b5790.mp4

**Comment by ChanpleCai** [comment]
啊这，我还没装过strartallback，我先看看能不能把搜索的问题解决。

**Comment by ChanpleCai** [comment]
> 关闭startallaback后是这样，在进行搜索时任务栏会自动合并，我认为这样很不自然。
> 
> 这是开启与关闭智能时的对比：
> 
> 通常：
> 
>  1.mp4 
> 开启软件后：
> 
>  3.mp4

这个在我的机子上复现不了。

**Comment by ChanpleCai** [comment]
装了个StartAllBack。修了下，提交商店在审核了。

**Comment by 123de234** [comment]
Thanks and I'll try it on !

**Comment by ChanpleCai** [comment]
> Thanks and I'll try it on !

刚通过审核。。

**Comment by 123de234** [comment]
和置顶的issue一样，新版本更新后闪退。

**Comment by ChanpleCai** [comment]
> 和置顶的issue一样，新版本更新后闪退。

审了三天，又发了个新的，你看看

**Comment by 123de234** [comment]
闪退问题已修复，但是问题还是在startallback软件下使用win+s会有闪烁 发件人: Chanple发送时间: 2021年11月9日 9:24收件人: ChanpleCai/SmartTaskbar抄送: ywf; Author主题: Re: [ChanpleCai/SmartTaskbar] 在使用开始菜单栏里的搜索功能时，之前的任务栏闪烁问题又会出现 (Issue #90) 和置顶的issue一样，新版本更新后闪退。审了三天，又发了个新的，你看看—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 123de234** [comment]
没问题了
