### ISSUE TITLE
RountedTB crashes when running with SmartTaskbar - Windows 11

### ISSUE THREAD

**Issue by khushrxnx** [ChanpleCai/SmartTaskbar#92]
RoundedTB is a cool application to make the taskbar look like a dock from MacOS, in Windows 11

When RoundedTB and SmartTaskbar are running together for a maximized window, there is a continuous white line blinking at the bottom of the screen.

Also, RoundedTB crashes after sometime when running along SmartTaskbar no matter what a window size maybe (maximized or not)

**Comment by ChanpleCai** [comment]
Are you using the latest window11 version in the app store or the old app (v1.1.9)?

**Comment by khushrxnx** [comment]
Yes, I'm using the app store version. This particular bug is due to RoundedTB's incompatibility with Auto Hide. Just wanted to raise this issue here too

**Comment by ChanpleCai** [comment]
Received, let me figure it out.

**Comment by ChanpleCai** [comment]
I found that as long as the auto-mode is turned on, it will keep flashing, and there is no conflict with the SmartTaskbar.As for the crashing issue, I’m still observing.

**Comment by khushrxnx** [comment]
This issue seems to be resolved with the lastest updates of SmartTaskbar and Beta version of RoundedTB
