### ISSUE TITLE
连接显示器使用的时候缩小全屏应用会出现应用时大时小的情况

### ISSUE THREAD

**Issue by Fatpandac** [ChanpleCai/SmartTaskbar#97]
**Describe the bug**
最大化应用再还原应用大小时，会出现应用闪屏

**To Reproduce**
1. 笔记本外接显示器，使用显示器为主显示
2. 全屏浏览器 smarttaskbar 智能隐藏，之后再点击 最大化 图标就会出现应用闪屏现象

**Desktop (please complete the following information):**
 - OS: Win 11
 - Version 21H2

**Comment by ChanpleCai** [comment]
收到

**Comment by ChanpleCai** [comment]
收到

**Comment by ChanpleCai** [comment]
试着修了一下，提交审核了，应该要过几天才可以获取到，到时候试试

**Comment by Fatpandac** [comment]
> 试着修了一下，提交审核了，应该要过几天才可以获取到，到时候试试

好的，谢谢了🙏

**Comment by Fatpandac** [comment]
解决了
感谢🙏
