### ISSUE TITLE
Windows 11 无法在屏幕右下角调出任务栏

### ISSUE THREAD

**Issue by SteveZhu0241** [ChanpleCai/SmartTaskbar#99]
当全屏运行应用时，任务栏自动隐藏。通常情况下当鼠标移动到任务栏时，任务栏会自动弹出。然而当鼠标移动到屏幕的右下角时，却无法调出任务栏，必须将鼠标移动到屏幕底端的较中部，才能够成功调出任务栏。

并且还额外发现了一个 bug，在显示桌面时点击右下角的控制中心，任务栏也会自动隐藏，尽管此时不是全屏状态。不知道这两个问题是否有所关联。

感谢！

**Comment by ChanpleCai** [comment]
这个是Windows 11本来就这样，你可以试试，只开自动自带的自动隐藏任务栏，鼠标移动到右下角是不会弹出任务栏的。
新模式是判断窗口相交就自动隐藏，不再依据最大化了。最大化的判断有太多问题，所以我全改了。

**Comment by SteveZhu0241** [comment]
> 这个是Windows 11本来就这样，你可以试试，只开自动自带的自动隐藏任务栏，鼠标移动到右下角是不会弹出任务栏的。 新模式是判断窗口相交就自动隐藏，不再依据最大化了。最大化的判断有太多问题，所以我全改了。

原来如此，了解了。

感谢回复！
